### ISSUE TITLE
Problem Set 1 running questions

### ISSUE THREAD

**Issue by DeAngelisA** [UniLuFS2020-ReplicationSeminar/general-Q-A#4]
Feel free to post any questions regarding PS1 below this message.

**Comment by fabioklr** [comment]
Hi @DeAngelisA @mathi619 

I have trouble accessing the Landwehr and Ojeda (2020) article. When I try to access it at Cambridge University Press with an institutional login I get the following error message. Also notice the picture of the error in the attachment.

"The organisation you have selected has not submitted information to Cambridge University Press for their Shibboleth/Athens account. Therefore you cannot access Cambridge Core with this login.
Please notify your librarian to contact our Technical Support department for assistance in setting up this feature. They can contact Technical Support via academictechsupport@cambridge.org.
Error code: ERR_SHIB_UNKNOWN_ORG"
<img width="1433" alt="Screenshot 2021-03-11 at 15 35 43" src="https://user-images.githubusercontent.com/73608514/110803552-9825be80-827f-11eb-9e6f-2585db632da5.png">

**Comment by fabioklr** [comment]
@mathi619 was able to access the paper and we now both have it as a PDF. So far the issue is resolved.

**Comment by fabioklr** [comment]
@DeAngelisA @mathi619  and I couldn't create a private repo. It said that, by organization policy, this was not possible. Is there maybe a tick in the settings you could remove?

**Comment by DeAngelisA** [comment]
> @DeAngelisA @mathi619 and I couldn't create a private repo. It said that, by organization policy, this was not possible. Is there maybe a tick in the settings you could remove?

Good point, thanks for letting me see that. I have sent an email, for this first PS I will manually change it, so no worries.
