### ISSUE TITLE
Changeing working directory in a chunk

### ISSUE THREAD

**Issue by LucaKeiser** [UniLuFS2020-ReplicationSeminar/general-Q-A#6]
@DeAngelisA  
Somehow i am not able to change the working directory in a chunk.

I get this message:
_"The working directory was changed to C:/Users/LucaK/Desktop/GitHub/Quantitative Research Design II/Melyssa_Luca_Repo/Problem Set 1 inside a notebook chunk. The working directory will be reset when the chunk is finished running. Use the knitr root.dir option in the setup chunk to change the working directory for notebook chunks"_

Can someone help me out here?
Thanks!

**Comment by DeAngelisA** [comment]
@LucaKeiser : I think the problem is that you are trying to change the wd inside the Rmarkdown notebook. Try avoiding that and just using `here::here()` to set the paths relatively to the project root folder.

**Comment by DeAngelisA** [comment]
Also, check out the [RMarkdown's troubleshooting](https://r4ds.had.co.nz/r-markdown.html#troubleshooting) section in the book.

**Comment by LucaKeiser** [comment]
Worked! 
Thanks a lot!
