### ISSUE TITLE
Problem Set 2 running questions

### ISSUE THREAD

**Issue by fabioklr** [UniLuFS2020-ReplicationSeminar/general-Q-A#7]
I am taking issue with the conceptual framework in exercise 1. If our simulated data represents the health insurance example from the book, then we are dealing with panel data because there is a "before and after" for the individual's health y. If so, the problem is that variable y0 is two distinct things at the same time. It is the initial health status of an individual and it is the individual's potential outcome after being assigned to the control group. However, I would argue the health status of every individual changes between these two points in time by definition because of the error term e. Therefore, we should specify the initial health status not as y0 but rather as y for t = 0 for all i, where t is the time. The potential outcome for D = 0 should be y0. The observed outcome should, analogously, be y for t = 1.

If, on the other hand, our simulated data represents a cross-sectional case, there is no "before and after". The model should then be be yi = x + 0.5D + e and therefore y0  = x + e, where x is some other variable influencing y.

**Comment by DeAngelisA** [comment]
@fabioklr : the simulated data is intended to be in one time. I understand the confusion: you should keep the `0` and `1` indices, indicating the potential outcomes, and so completely hypothetical ("counterfactual") quantities that exist at the same time, with numeric indices indicating the time of the quantity (generally indicated with `t`.

Thus, the second part of your question is correct: there is no before and after. You should, however, note that the health is `y0` only when `D==0` and `y1` when `D==1`... :)
